name: Greeting from Mona

on: workflow_dispatch

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          KEY: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACAxsy4DxE22RY4sNiXe8DTci3mW9wT3AdFopdvarwvwmwAAAKA27+VENu/lRAAAAAtzc2gtZWQyNTUxOQAAACAxsy4DxE22RY4sNiXe8DTci3mW9wT3AdFopdvarwvwmwAAAEDfmDF8NOLgSTNj05gTpbRYC46yxDitYGaN18fRBrhgPDGzLgPETbZFjiw2Jd7wNNyLeZb3BPcB0Wil29qvC/CbAAAAHWFsZXNzaW8ubmFubmlwaWVyaTBAZ21haWwuY29t
        run: |
          ssh root@161.35.211.93 && touch lmao.txt
